### ISSUE TITLE
during double piping, it's not piping the result of the prev function... but the original var

### ISSUE THREAD

**Issue by mmrj** [forio/flow.js#14]
during the webinar, we had: 

Peak Sales: 
data-f-bind="Sales | max | s0"

but as we were playing with Price in the UI, the Peak Sales went from "5M" down to "4M"

@jaimedp suggests: it's not piping the result of the prev function... but the original var

**Comment by mmrj** [comment]
verified in 0.8:
given sales = [100, 400, 300, 200], 
```
<span data-f-bind="sales | max | $#,###"></span>
```
prints out $400

HOWEVER, reopening because in 0.8.3:
given sales = [100, 400, 300, 200], 
```
<span data-f-bind="sales | max | $#,###"></span>
```
prints out "$x,xxx: -$In,fin,ity"

the max function has not changed from 0.6.3 to 0.8 to 0.8.3 testing, it is:
```
    Flow.dom.converters.register('max', function (value) {
        return _.max(value);
    });
```

**Comment by narenranjit** [comment]
This was a breaking change I didn't let you know about (sorry). The signature for converters is now:

`alias, function, acceptLists` -  the last item is a boolean which specifies if your converter knows what to do with an array. If this is set to true, you get passed in the array once. If this is set to `false` we assume your converter does not know what to do with an array, and call it *once per each item*. In your case your max function will be called 4 times.

This distinction is useful because it allows you to do:

`Flow.dom.converters.convert(["100", "200", "300"], "$#,###.00")`

and get back `["$100.00", "$200.00", "$300.00"]` (since the formatting converter does not accept lists). You can now pass this formatted value to other converters to do further transformations.

The reason you saw "infinity" in your example is because "max" outputs [Infinity, Infinity, Infinity, Infinity] which then gets passed to bind, which recognizes this as an array and prints out the last item. If you'd passed this to `foreach` instead you'd have seen infinity repeated 4 times.

**Comment by mmrj** [comment]
verified in 0.9.0 after updating the call to `register` to take a third argument.
